### ISSUE TITLE
[BUG] 장전 후 총알의 숫자가 바뀌지 않는 오류

### ISSUE THREAD

**Issue by NR0503** [rhtmxm17/Project-LB#167]
## 버그 개요

무기를 장전했을 때, 총알의 숫자가 바뀌지 않습니다. 사격은 가능합니다. 다른 무기로 교환한 후 돌아오면 숫자가 바뀌어 있습니다. 총알의 숫자가 0이 되어 자동 장전될 때는 숫자가 바뀝니다.

**Comment by don72-s** [comment]
수정사항 확인했습니다.
