### ISSUE TITLE
[BUG] 플레이어가 몬스터의 추적 범위 안에서 벗어나면 몬스터가 추적을 중지하는 현상

### ISSUE THREAD

**Issue by GuGuJelly** [rhtmxm17/Project-LB#21]
우리가 원하는 구현: 몬스터의 추적 범위 안에서 벗어나도 몬스터가 계속 플레이어를 쫓아가기

버그상황: 플레이어가 몬스터의 추적 범위 안에서 벗어나면 몬스터가 추적을 중지하는 현상

진행상황: 진행중

**Comment by DARAMJJINY** [comment]
확인했습니다. 공유 감사합니다!

**Comment by GuGuJelly** [comment]
이슈 해결완료
