### ISSUE TITLE
[BUG] 사라진 몬스터가 공격하는 현상

### ISSUE THREAD

**Issue by don72-s** [rhtmxm17/Project-LB#48]
## 버그 개요

몬스터가 사라졌음에도 불구하고 다시 공격하는 현상

## 버그 상세

사라진 몬스터가 플레이어를 사라지기 전 위치에서 공격하여 null을 참조하는 현상이 발생.

**Comment by rhtmxm17** [comment]
디버깅중 사라진 몬스터가 공격하는 것이 아닌, CharacterController가 Collider를 상속해서 구현되어 있기 때문에 attachedrigidbody 참조에 실패한 것으로 확인됨
플레이어 로직과 플레이어 물리 판정 영역(피격에 사용할 Collider)의 태그를 구분해 해결함
